package product

const (
	ImportProductEndpoint           = "/v3/product/import"
	InfoProductEndpoint             = "/v1/product/import/info"
	ImportProductBySkuEndpoint      = "/v1/product/import-by-sku"
	UpdateProductAttributesEndpoint = "/v1/product/attributes/update"
	ImportProductPicturesEndpoint   = "/v1/product/pictures/import"
	ListProductEndpoint             = "/v3/product/list"
	InfoRatingBySkuProductEndpoint  = "/v1/product/rating-by-sku"
	ListProductByIdentifierEndpoint = "/v3/product/info/list"
	InfoProductAttributesEndpoint   = "/v4/product/info/attributes"
	ProductInfoDescriptionEndpoint  = "/v1/product/info/description"
	ProductsStocksV2Endpoint        = "/v2/products/stocks"
	ProductInfoStocksEndpoint       = "/v4/product/info/stocks"
	ImportProductsPricesEndpoint    = "/v1/product/import/prices"
	ProductInfoDiscountedEndpoint   = "/v1/product/info/discounted"
	ProductUpdateDiscountEndpoint   = "/v1/product/update/discount"

	ProductInfoLimitEndpoint           = "/v4/product/info/limit"
	ProductUpdateOfferIDEndpoint       = "/v1/product/update/offer-id"
	ProductArchiveEndpoint             = "/v1/product/archive"
	ProductUnarchiveEndpoint           = "/v1/product/unarchive"
	ProductsDeleteV2Endpoint           = "/v2/products/delete"
	ProductInfoSubscriptionEndpoint    = "/v1/product/info/subscription"
	ProductRelatedSKUGetEndpoint       = "/v1/product/related-sku/get"
	ProductPicturesInfoV2Endpoint      = "/v2/product/pictures/info"
	ProductInfoWrongVolumeEndpoint     = "/v1/product/info/wrong-volume"
	ProductPlacementZoneInfoEndpoint   = "/v1/product/placement-zone/info"
	ProductInfoWarehouseStocksEndpoint = "/v1/product/info/warehouse/stocks"
	ProductInfoStocksByWarehouseV2Fbs  = "/v2/product/info/stocks-by-warehouse/fbs"
	ProductInfoStocksByWarehouseV1Fbs  = "/v1/product/info/stocks-by-warehouse/fbs"
	ProductActionTimerUpdateEndpoint   = "/v1/product/action/timer/update"
	ProductActionTimerStatusEndpoint   = "/v1/product/action/timer/status"
	ProductInfoPricesV5Endpoint        = "/v5/product/info/prices"
)
